files {
    'index.html',
	'timeout.html',
    'music/kifflom.mp3',
    'music/loadscreen.mp3',
	'music/pause.mp3',
    'img/loading.gif',
	'img/loadscreen.jpg',
    'img/logo.png',
	'img/logo2.png',
	'img/bg-1.jpg',
    'img/bg-2.jpg',
	'img/bg-3.jpg',
	'img/bg-4.jpg',
    'img/bg-5.jpg',
	'img/bg-6.jpg',
	'img/bg-7.jpg',
    'img/bg-8.jpg',
	'img/bg-9.jpg',
	'img/bg-10.jpg',
    'img/timeout.png',
	'css/bootstrap.css',
    'css/owl.carousel.css',
	'css/style.css',
	'infobox/1.png',
	'infobox/2.png',
	'infobox/3.png',
	'infobox/4.png',
    'js/jquery.ajaxchimp.js',
	'js/jquery.backstretch.min.js',
    'js/jquery-1.11.0.min.js',
	'js/lj-safety-first.js',
    'js/owl.carousel.min.js',
}

loadscreen 'index.html'

resource_manifest_version '77731fab-63ca-442c-a67b-abc70f28dfa5'